name: call build
on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "my-webapp"
      environment: "production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
  test:
    needs: build
    uses: ./.github/workflows/resuable-build.yml
    with:
      app_name: "my-webapp"
      environment: "production"
    steps:
      - name: printing build_version output
        run: echo ${{ needs.build.outputs.VERSION }}
