on:
    workflow_run:
        workflows: ["Run Tests"]
        types: [completed]

jobs:
    condition:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: echo "This message is printed when workflow is triggered after successfull completion of another workflow"