name: github-hosted runners
on:
    push:
        branches: [main]

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - name: os name, runner's hostname and current user
              run: |
                echo "os name: ${{ runner.os }}"
                echo "runner hostname: ${{ runner.hostname }}"
                echo "current user: ${{ runner.user }}"

            

    windows:
        runs-on: windows-latest
        steps:
            - name: os name, runner's hostname and current user
              run: |
                echo "os name: ${{ runner.os }}"
                echo "runner hostname: ${{ runner.hostname }}"
                echo "current user: ${{ runner.user }}"


    macos:
        runs-on: macos-latest
        steps:
            - name: os name, runner's hostname and current user
              run: |
                echo "os name: ${{ runner.os }}"
                echo "runner hostname: ${{ runner.hostname }}"
                echo "current user: ${{ runner.user }}"
