name: multi-job
on:
    push:
        branches: [main]    
env: 
    APP_NAME: myapp
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: staging
        steps:
            - name: build
              env:
                VERSION: 1.0.0
              run: | 
                echo "Building the app"
                echo "The app name is $APP_NAME"
                echo "The environment is $ENVIRONMENT"
                echo "The version is $VERSION"
              
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: test
              run: echo "Running tests"
            - name: Run a specific script only on main branch
              if: github.ref == 'refs/heads/main'
              run: |
                echo "Running additional tests for main branch"
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: deploy
              run: echo "Deploying"