name: files to ignore
on: 
    push:
        branches:
            - main
            - release/*

        paths-ignore:
     
            - '*.md'
            - 'docs/**'
obs:
    path_to_ignore:
        runs-on: ubuntu-latest