name: smart triggers
on: 
    push:
        branches:
            - main
            - release/*
        paths:
            - 'src/**'
            - 'app/**'
        paths-ignore:
     
            - '*.md'
            - 'docs/**'
