name: smart triggers
on: 
    push:
        branches:
            - main
            - release/*
        paths:
            - 'src/**'
            - 'app/**'
jobs:
    path_to_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: branch where workflow is
              run: echo "${{ github.ref_name }}"