name: Run Tests
on:
    push:
        branches: 

jobs:
    tests:
        runs-on: ubuntu-latest
        step
            - name: Running test
              run: echo "The tests are running" 